#!/usr/bin/env python3
"""Check the static site generated by the upstream SDK documentation template."""

import argparse
from html.parser import HTMLParser
import json
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]


class References(HTMLParser):
    def __init__(self):
        super().__init__()
        self.targets = set()

    def handle_starttag(self, tag, attrs):
        for name, value in attrs:
            if value and (name == "src" or (name == "href" and tag in {"a", "link"})):
                self.targets.add(value)


def check_site(output, versioned=False):
    required = ["index.html"]
    if versioned:
        versions = json.loads((ROOT / ".github/versions.json").read_text(encoding="utf-8"))
        for version in versions["versions"]:
            prefix = version["url_path"]
            required.extend(f"{prefix}/{name}" for name in (
                "index.html", "index_zh.html", "index_en.html", "version_config.json",
                "_static/project_info.json", "_static/GD32H77D-Gino.pdf",
                "_static/GD32H77D-Gino_EN.pdf",
            ))
    missing = [name for name in required if not (output / name).is_file()]
    pages = sorted(output.rglob("*.html"))
    for page in pages:
        parser = References()
        parser.feed(page.read_text(encoding="utf-8"))
        for target in sorted(parser.targets):
            parsed = urlsplit(target)
            if parsed.scheme or parsed.netloc or not parsed.path:
                continue
            path = unquote(parsed.path)
            resolved = (output / path.lstrip("/") if path.startswith("/")
                        else page.parent / path).resolve()
            if resolved.is_dir():
                resolved /= "index.html"
            if not resolved.is_relative_to(output) or not resolved.is_file():
                missing.append(f"{page.relative_to(output)}: {target}")
    if missing:
        raise ValueError("Missing documentation targets:\n" + "\n".join(missing))
    print(f"Checked {len(pages)} HTML pages: all local links and assets exist")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--versions", action="store_true")
    args = parser.parse_args()
    check_site(args.output.resolve(), args.versions)
